### ISSUE TITLE
Ajustar branches

### ISSUE THREAD

**Issue by JDaniielC** [ribaline/login_unimedBH#1]
Seu projeto está na branch main enquanto o padrão de branch é master.

- [x] Melhorar README (Tire uma foto do seu projeto em andamento e coloca nele.
- [ ] Coloque main como default de branch.
- [ ] Jogue seu README atualizado na main.

**Comment by ribaline** [comment]
@JDaniielC ei tudo bem?
Muito obrigada pelas dicas!
Uma dúvida: meu git local está confugurado como Master, assim toda vez que dou um push da máquina para o github vem como uma nova branch e não estou conseguindo mudar isso.
Você consegue me ajudar?
obs: ja tentei dar merge e rebase e também não consegui resolver isso!

**Comment by JDaniielC** [comment]
Possibilidades:
1. Mudar no Github: No repositório, vá para settings > branches e modifique o default branch para a master.
2. Dar git push na main: Ao fazer o push, você pode rodar "git push origin main -f" ele vai forçar o push.
3. Rode os seguintes comandos:
`
git checkout main
git pull origin master --allow-unrelated-histories (ou git merge)
git push origin main
`

Se em algum dos seus comandos de merge/rebase ocorrer um problema de unrelated histories, basta rodar o mesmo comando com --allow-unrelated-histories.
O que está acontecendo, é que provavelmente você criou um repositório local, realizou todo o código nele, então depois criou um repositório online com README (ou seja, já com um commit inicial), de forma que as histórias do seu main (remoto) e master (local) são diferentes.
No mais, eu aconselho que você atualize o seu git, não é mais utilizado master, nas novas versões são main ;D

**Comment by JDaniielC** [comment]
Resolveu?
